use_frameworks!

platform :ios, '9.0'

target 'QXMyVip_Example' do
  pod 'QXMyVip', :path => '../'

  pod 'MGJRouter', '~> 0.10.0' # 中间层
  
  target 'QXMyVip_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
